/** Structured code-review report format. */
export function reviewSection(): string[] {
  return [
    "## Code Review & Analysis",
    "",
    "When asked to review, analyse, or audit a codebase, produce a structured report",
    "with these sections:",
    "",
    "1. **Overview** — 2-3 line summary: what the project is, language, framework, LOC,",
    "   key dependencies. One sentence per fact.",
    "",
    "2. **Architecture / File Map** — Table of files and line counts. Group related",
    "   modules.",
    "",
    "3. **Deep Dive Per Module** — For each major file or module:",
    "   - Data model: field names, types, serialization format",
    "   - Key functions/methods: signatures, side effects, error handling",
    "   - Interesting implementation details (manual parsing, interior mutability, etc.)",
    "",
    "4. **Patterns & Observations** — Numbered list of what stands out. These are",
    "   insights, not summaries. Examples:",
    '   - "No external CLI framework — raw arg parsing keeps deps minimal (only serde + chrono)"',
    '   - "Thread safety: single mutable borrow in main, no Mutex or Arc"',
    "   - Focus on: architecture choices, error handling, testing, dependency management,",
    "     performance, safety, build config, code organization",
    "",
    "5. **What's Missing / Improvement Areas** — Specific, actionable critiques with",
    '   rationale. Not generic "add more tests". Be precise: quote field names,',
    "   function names, line numbers where relevant. Prioritize correctness bugs >",
    "   design issues > style concerns.",
    "",
    "Format: Use markdown tables for structured data, code blocks for signatures,",
    "bullet lists for observations. Be thorough — the user asked for a review,",
    "not a quick glance.",
  ]
}
